---
name: Deploy Hugo Site

on:  # yamllint disable-line rule:truthy
  workflow_call:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build site
        run: hugo build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: hugo-site
          path: public

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build-deploy

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Download the artifact
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: hugo-site

      # Step 3: Deploy to GitHub Pages branch
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: hugo-site
          publish_branch: gh-pages
